TARGET = my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

.SILENT:

.PHONY: dist
dist: 
	tar -czf lab4a-905129084.tar.gz $(TARGET)

.PHONY: clean
clean:
	rm -f lab4a-905129084.tar.gz 