#NAME: Yuxin Wang,Qingyuan Pan
#EMAIL: yuxinwanghailey@outlook.com,qingyuan2018pan@sina.com
#ID: 905129084,405101723

.SILENT:

default:
	gcc -Wall -Wextra -g -o lab3a lab3a.c

dist:
	tar -czf lab3a-905129084.tar.gz lab3a.c Makefile README ext2_fs.h

clean:
	rm -rf lab3a lab3a-905129084.tar.gz